name: Horusec Scan

on:
  push:
    branches:
      - main

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
        
    - name: Checkout código-fonte
      uses: actions/checkout@v2
      
    - name: Instalar Horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
    
    - name: Executar análise de segurança
      run: |
        horusec start -p ./RotasCaminhao -e="true"
