name: Horusec Scan

on:
  push:
    branches:
      - main

jobs:
  horusec:
    runs-on: ubuntu-latest

    container:
      image: docker:20.10.9 # Use uma versão compatível do Docker

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Instalar Horusec
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

    - name: Executar análise de segurança
      run: |
        horusec start -p ./RotasCaminhao -e="true"
