name: Horusec Scan

on:
  push:
    branches:
      - main # Defina a branch de destino aqui

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

   
        
    - name: Instalar Horusec
      run: |
        curl -fsSL https://horusec.io/bin/install.sh | bash -s latest

    - name: Configurar Horusec
      run: |
        echo -e '{"horusecAuth": {"horusecAPIUri": "https://api.horusec.io", "horusecAPIKey": "${{ secrets.HORUSEC_TOKEN }}"}}' > horusec-config.json

    - name: Debug PATH
      run: |
        echo $PATH
    - name: Listar Conteúdo do Diretório
      run: |
        ls -l
    - name: Executar análise de segurança
      run: |
        horusec start -p ./RotasCaminhao --config-file horusec-config.json --output-format table
